services:
  app1:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    # ports:
    #   - 8082:443
    volumes:
      - ./Cert/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  app2:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  app3:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  app4:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert/aspnetapp.pfx:/https/aspnetapp.pfx:ro

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./Conf/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8080:8080
  #   cpus: 2

  haproxy:
    image: haproxy
    volumes:
      - ./Conf/haproxy:/usr/local/etc/haproxy:ro
      # - ./Cert/local.host.dev+2.pem:/https/aspnetapp.pem:ro
      # - ./Cert/local.host.dev+2-key.pem:/https/aspnetapp.pem.key:ro
    ports:
      - 8081:8080
      - 8404:8404

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./Monitor/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./Cert/rootCA.pem:/https/rootCA.pem:ro
      - ./Cert/rootCA-key.pem:/https/rootCA-key.pem:ro
      - prometheus-data:/prometheus

volumes:
  prometheus-data: