services:
  app1:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert:/https:ro

  app2:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert:/https:ro

  app3:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert:/https:ro

  app4:
    image: sampleapp:latest
    # restart: always
    environment:
      ASPNETCORE_URLS: "http://+;https://+;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: changeit
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - ./Cert:/https:ro

  nginx:
    image: nginx
    volumes:
      - ./Conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    cpus: 2

  haproxy:
    image: haproxy
    volumes:
      - ./Conf/haproxy:/usr/local/etc/haproxy:ro
    ports:
      - 8081:8080
      - 8404:8404